import { InjectionToken } from '@angular/core'

const DEFAULT_RING_WIDTH_TOKEN = new InjectionToken<number>('RING_WIDTH_TOKEN')
const DEFAULT_RING_WIDTH_VALUE = 10

const DEFAULT_PIE_VALUE_TOKEN = new InjectionToken<number>('PIE_VALUE_TOKEN')
const DEFAULT_PIE_VALUE = 0

const DEFAULT_BACKGROUND_TOKEN = new InjectionToken<string>('BACKGROUND_TOKEN')
const DEFAULT_BACKGROUND_VALUE = '#22d294'

export {
  DEFAULT_RING_WIDTH_TOKEN,
  DEFAULT_RING_WIDTH_VALUE,
  DEFAULT_PIE_VALUE_TOKEN,
  DEFAULT_PIE_VALUE,
  DEFAULT_BACKGROUND_TOKEN,
  DEFAULT_BACKGROUND_VALUE
}
